import createMDX from "@next/mdx";
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  pageExtensions: ["ts", "tsx", "md", "mdx", "js", "jsx"],
  experimental: {
    viewTransition: true,
  },
  async rewrites() {
    return {
      // beforeFiles: must outrank the app router's "/" match
      beforeFiles: [
        // terminal clients hitting the homepage get the plain-text version
        // (public/index.txt, generated by scripts/build-agent-md.mjs)
        {
          source: "/",
          has: [
            {
              type: "header",
              key: "user-agent",
              value: "(curl|[Ww]get|HTTPie)/.*",
            },
          ],
          destination: "/index.txt",
        },
      ],
      afterFiles: [],
      fallback: [],
    };
  },
  async redirects() {
    return [
      {
        source: "/",
        has: [
          {
            type: "query",
            key: "draw",
            value: "true",
          },
        ],
        destination: "https://draw.kkrll.com",
        permanent: false,
      },
    ];
  },
};

const withMDX = createMDX({
  options: {
    remarkPlugins: [],
    rehypePlugins: [],
  },
});

export default withMDX(nextConfig);
